name: "LeetCode CI"

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

defaults:
  run:
    shell: bash

jobs:
  problems:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: .

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install Yarn
        run: npm install -g yarn

      - name: Install npm Modules
        run: yarn install

      - name: Lint
        run: yarn lint

      - name: Prettier
        run: yarn prettier

      - name: Type Check
        run: yarn typecheck
